version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 150

[[analyzers]]
name = "test-coverage"